name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows MinGW,  os: windows-2022, shell: msys2 }
        - { name: Linux GCC,      os: ubuntu-latest }
        - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS,          os: macos-latest  }
        config:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up MSYS2 (Windows only)
      if: matrix.platform.name == 'Windows MinGW'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          git

    - name: Configure
      run: |
        if [[ "${{ matrix.platform.name }}" == "Windows MinGW" ]]; then
          cmake -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.config.flags }}
        else
          cmake -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.platform.flags }} ${{ matrix.config.flags }}
        fi

    - name: Build
      run: |
        if [[ "${{ matrix.platform.name }}" == "Windows MinGW" ]]; then
          cmake --build build
        else
          cmake --build build --config Release
        fi

    - name: Run Smoke Test
      run: |
        if [[ "${{ matrix.platform.name }}" == "Windows MinGW" ]]; then
          ./build/main.exe
        else
          ./build/main
        fi
